pipeline {
    agent any
    stages {
        stage('E2E_test_pipeline') {
            steps {
                echo "Pipeline-1."
                echo "MY_PARAM=${env.MY_PARAM}"
            }
        }
    }
}