pipeline {
    agent any
    stages {
        stage('Pipeline-1') {
            steps {
                echo "Pipeline-1."
                echo "MY_PARAM=${env.MY_PARAM}"
            }
        }
    }
}